# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: game-test
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: mmarci96/proxy:latest
          ports:
            - containerPort: 80
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: game-test
spec:
  selector:
    app: proxy
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxy-rolebinding
  namespace: game-test
subjects:
  - kind: ServiceAccount
    name: default
    namespace: game-test
roleRef:
  kind: Role
  name: proxy-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: game-test
  name: proxy-role
rules:
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
